services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongPass123!"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlData:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "true"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      db_server: sqlserver
      db_name: cars_db
      db_user: sa
      db_password: "StrongPass123!"
    depends_on:
      sqlserver:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  sqlData:
